### PR TITLE
Remove div wrapper

### PR DESCRIPTION
**Pull request by bryceosterhaus**
Can we just remove this wrapper? Adds unnecessary markup to DOM when we don't need it.

### CODE REVIEW

**Comment by mairatma** [comment]
We need it if more than one child component is passed, since components can't render more than one child at the root. 

I understand why you don't like the wrapper though. There are a few ways that we could handle this.
(1) Only add the wrapper when more than one child is passed
(2) Warn when more than one child is passed and only render the first

`react-redux` follows (2), so maybe that would make more sense for us :)

**Comment by bryceosterhaus** [comment]
Ah I see. I had thought about that, but didn't think passing more than one child was ever recommended.

We could a combination of both? If someone really wants to pass more than one child, they can, but we would recommend against doing so. If they do still pass more than one child, it would wrap in a span so that we don't get the block styling of a div.

**Comment by mairatma** [comment]
Nice, I like the idea of doing both. I don't think we need to recommend against it though, do you know why that would be bad? The only bad thing I can thing of is the wrapper being unexpected maybe, so we can warn about that.

**Comment by bryceosterhaus** [comment]
I guess we actually wouldn't need to recommend against it, I wonder why react-redux doesn't work with more than one child, seems like a more app architectural decision.

**Comment by mthadley** [comment]
Offering my 2 cents:

I'm assuming they use `Children.only` because `Provider` is only meant to *decorate* it's child component through additional `context`, without affecting any other behavior like introducing more DOM elements. It's already been mentioned, but allowing more than one child would force `Provider` to wrap it's children, which would be violating this intent.

I suppose there might be other reasons, like the child should really be the root of your component tree or `App`, and so having more than one root in a single tree through multiple children doesn't really make sense.

Either way, I think as long as `metal-redux` is "compatible" with `react-redux`, I am happy. So if we offer a superset of their API where `Provider` can have multiple children but they must be wrapped, I think it would be just fine.

**Comment by bryceosterhaus** [comment]
Just updated pr to allow for either one or multiple children

**Comment by mairatma** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mairatma** [comment]
Merged, thanks!

**Pull request closed without merging**
